import numpy as np

X = np.array([2, 5, 3, 1, 7])
Y = np.array([2, 1, 8, 5, 7, 9])
print("Median X = ", np.median(X))
print("Median Y = ", np.median(Y))
print()
print("median có thể tính theo các trục với mảng nhiều chiều")
print()
arr = np.array([[7, 4, 2], [3, 9, 5]])
print("median arr (axis = 0) = ", np.median(arr, axis=0))
print("median arr (axis = 1) = ", np.median(arr, axis=1))
print()
print("tính Số người truy cập trung bình mỗi ngày trong tuần qua của Freetuts")
print()
freetuts_visitors = np.array([3776, 3112, 3476, 3319, 3559, 50293, 30432]) # 2 giá trị cuối lệch xa so với các giá trị trong dãy
print("tính theo Mean = : ", np.mean(freetuts_visitors))
print("tính theo Median = : ", np.median(freetuts_visitors))
print()
print("bỏ qua các phần tử có giá trị nan trong mảng khi tính mean và median")
print()
x = np.array([2, np.nan, 5, 9])
print("mean = ", np.nanmean(x))
print("median = ", np.nanmedian(x))
print("Nếu như sử dụng mean và median thông thường thì kết quả trả về sẽ là nan:")
print("mean = ", np.mean(x))
print("median = ", np.median(x))